package GUI;

public enum CharEnum
{
    // 0 - 15
    NULL, SMILEY_STENCIL, SMILEY, HEART, 
    DIAMOND, CLUB, SPADE, DOT, 
    DOT_INVERTED, CIRCLE_STENCIL, CIRCLE_STENCIL_INV, MARS, 
    VENUS, NOTE_SINGLE, NOTE_DOUBLE, BURST,
    
    // 16-31
    TRIANGLE_RIGHT, TRIANGLE_LEFT, ARROWS_VERTICAL, DOUBLE_EXCLIMATION_MARK, 
    PARAGRAPH_MARK, SWIRL, UNDERSCORE_THICK, ARROWS_VERTICAL_UNDERSCORED, 
    ARROW_UP, ARROW_DOWN, ARROW_RIGHT, ARROW_LEFT, 
    NEWLINE_CHAR, ARROWS_HORIZONTAL, TRIANGLE_UP, TRIANGLE_DOWN,
    
    // 32-47
    SPACE, EXCLIMATION_MARK, DOUBLE_QUOTE, POUND, 
    DOLLAR_SIGN, PERCENT, AMPERSAND, APOSTROPHE, 
    PARENTHESIS_LEFT, PARENTHESIS_RIGHT, ASTERISK, PLUS, 
    COMMA, DASH, PERIOD, SLASH,
    
    // 48 - 63
    ZERO, ONE, TWO, THREE,
    FOUR, FIVE, SIX, SEVEN,
    EIGHT, NINE, COLON, SEMICOLON, 
    ANGLED_BRACKET_LEFT, EQUALS, ANGLED_BRACKET_RIGHT, QUESTION_MARK;
    // 64 - 79
    
    // 80 - 95
    
    // 96 - 111
    
    // 112 - 127
    
    // 128 - 143
    
    // 144 - 159
    
    // 160 - 175
    
    // 176 - 191
    
    // 192 - 207
    
    // 208 - 223
    
    // 224 - 239 
    
    // 240 - 255
}